//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewEmployee.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tbl_Country
    {
        public tbl_Country()
        {
            this.tbl_city = new HashSet<tbl_city>();
        }
        [Key]
        public int cou_Id { get; set; }
        public string cou_Name { get; set; }
    
        public virtual ICollection<tbl_city> tbl_city { get; set; }
    }
}
