//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeMvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_EmployeeDetails
    {
        public int empdet_id { get; set; }
        public int empdet_empId { get; set; }
        public string empdet_FirstName { get; set; }
        public string empdet_MiddleName { get; set; }
        public string empdet_LastName { get; set; }
        public int empdet_CityId { get; set; }
        public string empdet_residentialAddress { get; set; }
        public string empdet_residentialPostCode { get; set; }
    
        public virtual tbl_city tbl_city { get; set; }
        public virtual tbl_Employee tbl_Employee { get; set; }
    }
}
